# Generated by Django 2.0.6 on 2018-06-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=10)),
                ('route', models.CharField(max_length=10)),
                ('journey_time', models.CharField(max_length=100)),
                ('bus_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=5)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dublinbusapp.Bus')),
            ],
        ),
    ]
